name: 'Publish application'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET 7.0 SDK
        - name: Setup .NET 7 preview
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '7.0.x'
            include-prerelease: true

        # Added Ahead-Of-Time workload
        - name: Add AOT Workload
          run: dotnet workload install wasm-tools
          
        # Generate the website
        - name: Publish
          run: dotnet publish samples/KristofferStrube.Blazor.GraphEditor.WasmExample/KristofferStrube.Blazor.GraphEditor.WasmExample.csproj --configuration Release --output build

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: build/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
